version: '3.9'

services:
  master:
    image: chrislusf/seaweedfs
    command: "master -ip=master -port=9333"
    ports:
      - "9333:9333"

  volume:
    image: chrislusf/seaweedfs
    command: "volume -max=5 -ip=volume -mserver=master:9333 -port=8080 -dir=/data"
    volumes:
      - seaweed_data:/data
    ports:
      - "8080:8080"

  fuse:
    image: chrislusf/seaweedfs
    privileged: true
    cap_add:
      - SYS_ADMIN
    entrypoint: ["sh", "-c"]
    command: >
      "sleep 5 &&
      mkdir -p /mnt/seaweed &&
      weed mount -dir=/mnt/seaweed -filer=filer:8888"
    volumes:
      - seaweed_mount:/mnt/seaweed
    depends_on:
      - master
      - volume
      - filer

  filer:
    image: chrislusf/seaweedfs
    command: "filer -master=master:9333 -port=8888"
    depends_on:
      - master
      - volume
    ports:
      - "8888:8888"

  foundationdb:
    image: foundationdb/foundationdb:7.1.27
    ports:
      - "4500:4500"
    environment:
      - FDB_NETWORKING_MODE=host
    volumes:
      - fdb_data:/var/lib/foundationdb

  pulsar:
    image: apachepulsar/pulsar:3.1.0
    command: bin/pulsar standalone
    environment:
      advertisedAddress: localhost
    ports:
      - "6650:6650"
      - "8081:8080"
    volumes:
      - pulsar_data:/pulsar/data

volumes:
  seaweed_data:
  seaweed_mount:
  fdb_data:
  pulsar_data:
